# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='sentiment_polarity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
